# version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: content_db
      MYSQL_USER: content_user
      MYSQL_PASSWORD: content_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
