name: Deploy to EC2

#trigger
on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip source files
        run: zip -r deploy.zip . -x "*.git*"

      - name: Upload to s3
        run: |
          aws s3 cp deploy.zip s3://deploy-resource-01/deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name flask \
            --deployment-group-name flask-backend-api-group \
            --s3-location bucket=deploy-resource-01,bundleType=zip,key=deploy.zip \
            --file-exists-behavior OVERWRITE
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ap-northeast-2